# Generated by Django 3.0.6 on 2020-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('news_body', models.CharField(max_length=300)),
                ('news_outlet', models.CharField(max_length=80)),
            ],
        ),
    ]
